### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by sooyoung-wind** [sooyoung-wind/gh-flow-practice#2]
## Tasks

- [x] Print fizz, if i is multiple of 3.
- [x] Print buzz, if i is multiple of 5.
- [x] Print fizzbuzz, if i is multiple of 15.
- [x] Otherwise, print i itself.

## References

-[Fizzbuzz wikipedia](https://en.wikipedia.org/wiki/Fizz_buzz)
